name: CI Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'
  pull_request:

jobs:
  envmatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - run: echo 'matrix={"starenv":["root5","root6"],"compiler":["gcc485","gcc11"]}' >> "$GITHUB_OUTPUT"
        id: set-matrix

  build:
    runs-on: ubuntu-latest
    name: build-${{ matrix.starenv }}-${{ matrix.compiler }}
    needs: envmatrix
    strategy:
      matrix: ${{ fromJSON(needs.envmatrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            starenv=${{ matrix.starenv }}
            compiler=${{ matrix.compiler }}
          tags: star-spack
          outputs: type=docker,dest=/tmp/star-spack-${{ matrix.starenv }}-${{ matrix.compiler }}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: star-spack-${{ matrix.starenv }}-${{ matrix.compiler }}
          path: /tmp/star-spack-${{ matrix.starenv }}-${{ matrix.compiler }}.tar

  test:
    runs-on: ubuntu-latest
    name: test-${{ matrix.starenv }}-${{ matrix.compiler }}
    strategy:
      matrix: ${{ fromJSON(needs.envmatrix.outputs.matrix) }}
    needs: [envmatrix, build]
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: star-spack-${{ matrix.starenv }}-${{ matrix.compiler }}
          path: /tmp/

      - run: docker load --input /tmp/star-spack-${{ matrix.starenv }}-${{ matrix.compiler }}.tar
      - run: docker run star-spack modulecmd bash avail

  tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.envmatrix.outputs.matrix) }}
    needs: [envmatrix, test]
    steps:
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: star-spack-${{ matrix.starenv }}-${{ matrix.compiler }}
          path: /tmp/

      - run: echo "REFTAG=${{ steps.branch-name.outputs.current_branch }}-${{ matrix.starenv }}-${{ matrix.compiler }}" >> $GITHUB_ENV
      - run: docker load --input /tmp/star-spack-${{ matrix.starenv }}-${{ matrix.compiler }}.tar
      - run: docker tag star-spack ghcr.io/star-bnl/star-spack:${REFTAG}
      - run: docker push ghcr.io/star-bnl/star-spack:${REFTAG}
