name: Pull Request Build

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: build-${{ matrix.starenv }}-${{ matrix.compiler }}
    strategy:
      matrix:
        starenv: [root5, root6]
        compiler: [gcc485, gcc11]
    uses: ./.github/workflows/build.yaml
    with:
      starenv: ${{ matrix.starenv }}
      compiler: ${{ matrix.compiler }}
      optimize-runtime: false
