name: Release Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build-${{ matrix.starenv }}-${{ matrix.compiler }}
    strategy:
      matrix:
        starenv: [root5, root6]
        compiler: [gcc485, gcc11]
    uses: ./.github/workflows/build.yaml
    with:
      starenv: ${{ matrix.starenv }}
      compiler: ${{ matrix.compiler }}
      optimize-runtime: true
      image-tag: ${{ github.ref_name }}
